### ISSUE TITLE
ユーザー名を設定すると表示名で表示されず、ユーザー名が優先されて表示されてしまう

### ISSUE THREAD

**Issue by mamedachi** [pure-adachi/discord-chooooser#4]
- 最近、一意な名前を登録しろと、Discordから催促され、一意な名前を登録すると、その名前が優先的に表示されてしまう。
- 一意な名前を登録する前
  - ![IMG_0215](https://github.com/pure-adachi/discord-chooooser/assets/30336118/a9f6b838-5fa7-44ce-aa99-58a18901f658)
  - 表示名がなく、ユーザー名がデフォルトの名称となっている
- 一意な名前を登録した後
  - ![スクリーンショット 2023-06-19 23 32 42](https://github.com/pure-adachi/discord-chooooser/assets/30336118/7725fbbd-e8e4-45aa-8028-f7488f9232f1)
  - 表示名がデフォルトの名称となり、ユーザー名が一意な名称となる
- 処理的には、`member.nickname || member.user.username`としているが、`member.displayName`でよかった
  - [ソース](https://github.com/discordjs/discord.js/pull/9512/files#diff-7345774e86d9a3268ff114a30612ca2092c6c54b032efdce92a90ac8ca74d098L246)
- `discord.js`のバグであり、その対応はマージされている
  - [対応のPR](https://github.com/discordjs/discord.js/pull/9512) 
- しかし、[こちらのissue](https://github.com/Yes-Theory-Fam/yesbot-ts/issues/993)にあるようにまたリリースされていないので、リリース待ちとなる。

**Comment by mamedachi** [comment]
https://github.com/MT-CTF/ctf-discord-bot/issues/16#issuecomment-1613564351

v14.12待ち

**Comment by mvarendorff** [comment]
Heyyo! Checking in because you referenced one of my issues :) [discord.js 14.12.0](https://github.com/discordjs/discord.js/releases/tag/14.12.0) added support for the new username system (latest version currently is 14.12.1), so after upgrading you should be able to use `member.displayName` to reliably access the name displayed in the client.

**Comment by mamedachi** [comment]
@geisterfurz007 

Thank you for teaching me! Thanks to you, the problem has been solved. I'm grateful!
